version: '3.8'
name: otbr
services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    container_name: database
    env_file:
      - '.env'
    networks:
      - canary-net
    ports:
      - '$MYSQL_PORT:3306'
    volumes:
      - 'db-volume:/var/lib/mysql'
      - ../schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect"]
      interval: 10s
      timeout: 5s
      retries: 10
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.devnobuild
    restart: unless-stopped
    env_file:
      - '.env'
    networks:
      - canary-net
    ports:
      - '$gameProtocolPort:$gameProtocolPort'
      - '$statusProtocolPort:$statusProtocolPort'
    volumes:
      - '../:/canary'
      - '../build/linux-release/bin/canary:/bin/canary'
    depends_on:
      database:
        condition: service_healthy
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - canary-net
    volumes:
      - '../:/srv'
      - '../www/nginx-sample.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    links:
      - php-fpm
      - database
  php-fpm:
    build:
      context: ..
      dockerfile: docker/Dockerfile.php
    container_name: php-fpm
    networks:
      - canary-net
    volumes:
      - '../:/srv'
    links:
      - database
volumes:
  db-volume:
networks:
  canary-net:
    driver: bridge
